#!/bin/sh

#Modified by A.Shoda 2015/6/12

#SET RAMP TIME
tdswrite K1:VIS-PROTO_IM_SERVOF_L_TRAMP 5.0
tdswrite K1:VIS-PROTO_IM_SERVOF_T_TRAMP 5.0
tdswrite K1:VIS-PROTO_IM_SERVOF_V_TRAMP 5.0
tdswrite K1:VIS-PROTO_IM_SERVOF_R_TRAMP 5.0
tdswrite K1:VIS-PROTO_IM_SERVOF_P_TRAMP 5.0
tdswrite K1:VIS-PROTO_IM_SERVOF_Y_TRAMP 5.0
tdswrite K1:VIS-PROTO_TM_SERVOF_L_TRAMP 5.0
tdswrite K1:VIS-PROTO_TM_SERVOF_P_TRAMP 5.0
tdswrite K1:VIS-PROTO_TM_SERVOF_Y_TRAMP 5.0


#CLEAR HISTORY
#tdswrite K1:VIS-PROTO_F0_SERVOF_L_RSET 2
#tdswrite K1:VIS-PROTO_F0_SERVOF_T_RSET 2
#tdswrite K1:VIS-PROTO_F0_SERVOF_Y_RSET 2

#GAIN ON
tdswrite K1:VIS-PROTO_IM_SERVOF_L_GAIN -1.0
tdswrite K1:VIS-PROTO_IM_SERVOF_T_GAIN -1.0
tdswrite K1:VIS-PROTO_IM_SERVOF_V_GAIN -1.0
tdswrite K1:VIS-PROTO_IM_SERVOF_R_GAIN -1.0
#tdswrite K1:VIS-PROTO_IM_SERVOF_P_GAIN -1.0
#tdswrite K1:VIS-PROTO_IM_SERVOF_Y_GAIN -1.0
tdswrite K1:VIS-PROTO_TM_SERVOF_L_GAIN -1.0
#tdswrite K1:VIS-PROTO_TM_SERVOF_P_GAIN -1.0
#tdswrite K1:VIS-PROTO_TM_SERVOF_Y_GAIN -1.0



