#!/bin/sh

#Modified by A.Shoda 2015/6/12
#Modified by T.Sekiguchi 2015/08/03
#Changed from TAMA's one for KAGRA PR3
# by K.Okutomi 2016/1/20

#BLENDING OFF
#/users/sekiguchi/apps/blend_off.sh

#SET RAMP TIME
tdswrite K1:VIS-PR3_TM_DAMP_L_TRAMP 5.0
tdswrite K1:VIS-PR3_TM_DAMP_P_TRAMP 5.0
tdswrite K1:VIS-PR3_TM_DAMP_Y_TRAMP 5.0
tdswrite K1:VIS-PR3_TM_OLDAMP_P_TRAMP 5.0
tdswrite K1:VIS-PR3_TM_OLDAMP_Y_TRAMP 5.0
tdswrite K1:VIS-PR3_IM_DAMP_L_TRAMP 5.0
tdswrite K1:VIS-PR3_IM_DAMP_T_TRAMP 5.0
tdswrite K1:VIS-PR3_IM_DAMP_V_TRAMP 5.0
tdswrite K1:VIS-PR3_IM_DAMP_P_TRAMP 5.0
tdswrite K1:VIS-PR3_IM_DAMP_Y_TRAMP 5.0
tdswrite K1:VIS-PR3_IM_DAMP_R_TRAMP 5.0
tdswrite K1:VIS-PR3_GAS_DAMP_BF_TRAMP 5.0


#CLEAR HISTORY
tdswrite K1:VIS-PR3_TM_DAMP_L_RSET 2
tdswrite K1:VIS-PR3_TM_DAMP_P_RSET 2
tdswrite K1:VIS-PR3_TM_DAMP_Y_RSET 2
tdswrite K1:VIS-PR3_TM_OLDAMP_P_RSET 2
tdswrite K1:VIS-PR3_TM_OLDAMP_Y_RSET 2
tdswrite K1:VIS-PR3_IM_DAMP_L_RSET 2
tdswrite K1:VIS-PR3_IM_DAMP_T_RSET 2
tdswrite K1:VIS-PR3_IM_DAMP_V_RSET 2
tdswrite K1:VIS-PR3_IM_DAMP_P_RSET 2
tdswrite K1:VIS-PR3_IM_DAMP_Y_RSET 2
tdswrite K1:VIS-PR3_IM_DAMP_R_RSET 2


#GAIN ON
tdswrite K1:VIS-PR3_TM_DAMP_L_GAIN 0.5
tdswrite K1:VIS-PR3_TM_DAMP_P_GAIN 10.0
tdswrite K1:VIS-PR3_TM_DAMP_Y_GAIN 3.0
tdswrite K1:VIS-PR3_TM_OLDAMP_P_GAIN 30.0
tdswrite K1:VIS-PR3_TM_OLDAMP_Y_GAIN 10.0
tdswrite K1:VIS-PR3_IM_DAMP_L_GAIN 20.0
tdswrite K1:VIS-PR3_IM_DAMP_T_GAIN 100.0
tdswrite K1:VIS-PR3_IM_DAMP_V_GAIN 30.0
tdswrite K1:VIS-PR3_IM_DAMP_P_GAIN 300.0
tdswrite K1:VIS-PR3_IM_DAMP_Y_GAIN 10.0
tdswrite K1:VIS-PR3_IM_DAMP_R_GAIN 10.0
tdswrite K1:VIS-PR3_GAS_DAMP_BF_GAIN 1.0


#BF OFFSET
# tdswrite -sw K1:VIS-PROTO_GAS_COILOUTF_F2 OFFSET ON
# tdswrite -sw K1:VIS-PROTO_GAS_COILOUTF_F1 OFFSET ON
# tdswrite -sw K1:VIS-PROTO_GAS_COILOUTF_F0 OFFSET ON
