#! /usr/bin/env python
#
# This is a script based on K.Arai's automation script.
# This concatinates the hand-edited medms and creates a single medm.
#

import subprocess
import sys, os
import string, re
import optparse

# The below list shows the medm screens that are hand-edited beforehand
# are the ingredients to produce the final single medm screen.
#
# the list is in the format of:
# filename, horizontal offset [pixel], vertical offset [pixel]

height=187
hmergin=3

fname_list = [
    ['K1PEMIX1_IXV_GND_TR120Q_X_AA.adl',   (  10,  0)],
    ['K1PEMIX1_IXV_GND_TR120Q_Y_AA.adl',   (  10,  height+hmergin)],
    ['K1PEMIX1_IXV_GND_TR120Q_Z_AA.adl',   (  10,  2*(height+hmergin))],
]


# commented out 2018/03/15

#########################
# file read & write function
#########################
def read_write(f_name, hv_ofs):

    h_ofs = hv_ofs[0]
    v_ofs = hv_ofs[1]

    f=open(f_name)
    text_whole = f.read()
    f.close()


    points = 0

    text_lines = text_whole.split('\n')
    for line in text_lines:
        test_y = re.findall('y=(\\d+)',line)
        if test_y:
            coord=map(int,test_y)
            line = ' y='+str(v_ofs+coord[0])

        test_x = re.findall('[^i]x=(\\d+)',line)
        if test_x:
            coord=map(int,test_x)
            line = ' x='+str(h_ofs+coord[0])

        if points == 1:
            if '(' in line:
                coord=map(int,re.findall('\d+',line))
                if len(coord) == 2:
                    line = '(%d, %d)' %(coord[0]+h_ofs, coord[1]+v_ofs)
            else:
                points = 0

        if 'points' in line:
            points = 1

        print line
    
#########################
# Main routine
#########################

for cnt in range(len(fname_list)):
    read_write(fname_list[cnt][0], fname_list[cnt][1])


exit()
#########################
# leave a note
##########################
note = """text {
	object {
		x=220
		y=1155
		width=1111
		height=15
	}
	"basic attribute" {
		clr=44
	}
	textix="Generated by $HeadURL: https://redoubt.ligo-wa.caltech.edu/svn/cds_user_apps/trunk/lsc/common/medm/generateLSCoverview/generateLSCoverview.py $"
}
"""
print note
