#!/bin/sh

#CLEAR HISTORY
tdswrite K1:VIS-PROTO_F0_BLEND_SEISL_RSET 2
tdswrite K1:VIS-PROTO_F0_BLEND_SEIST_RSET 2
tdswrite K1:VIS-PROTO_F0_BLEND_SEISY_RSET 2

#SWITCH
tdswrite -sw K1:VIS-PROTO_F0_BLEND_SEISL FM3 ON
tdswrite -sw K1:VIS-PROTO_F0_BLEND_SEIST FM3 ON
tdswrite -sw K1:VIS-PROTO_F0_BLEND_SEISY FM3 ON
tdswrite -sw K1:VIS-PROTO_F0_BLEND_SEISL FM2 OFF
tdswrite -sw K1:VIS-PROTO_F0_BLEND_SEIST FM2 OFF
tdswrite -sw K1:VIS-PROTO_F0_BLEND_SEISY FM2 OFF
tdswrite -sw K1:VIS-PROTO_F0_BLEND_SEISL FM1 OFF
tdswrite -sw K1:VIS-PROTO_F0_BLEND_SEIST FM1 OFF
tdswrite -sw K1:VIS-PROTO_F0_BLEND_SEISY FM1 OFF
tdswrite -sw K1:VIS-PROTO_F0_BLEND_SEISL FM4 OFF
tdswrite -sw K1:VIS-PROTO_F0_BLEND_SEIST FM4 OFF
tdswrite -sw K1:VIS-PROTO_F0_BLEND_SEISY FM4 OFF
tdswrite K1:VIS-PROTO_F0_BLEND_SEISL_GAIN 1.0
tdswrite K1:VIS-PROTO_F0_BLEND_SEIST_GAIN 1.0
tdswrite K1:VIS-PROTO_F0_BLEND_SEISY_GAIN 1.0

tdswrite -sw K1:VIS-PROTO_F0_BLEND_LVDTL FM3 ON
tdswrite -sw K1:VIS-PROTO_F0_BLEND_LVDTT FM3 ON
tdswrite -sw K1:VIS-PROTO_F0_BLEND_LVDTY FM3 ON
tdswrite -sw K1:VIS-PROTO_F0_BLEND_LVDTL FM1 OFF
tdswrite -sw K1:VIS-PROTO_F0_BLEND_LVDTT FM1 OFF
tdswrite -sw K1:VIS-PROTO_F0_BLEND_LVDTY FM1 OFF
tdswrite -sw K1:VIS-PROTO_F0_BLEND_LVDTL FM4 OFF
tdswrite -sw K1:VIS-PROTO_F0_BLEND_LVDTT FM4 OFF
tdswrite -sw K1:VIS-PROTO_F0_BLEND_LVDTY FM4 OFF











