#!/bin/sh

#Modified by A.Shoda 2015/6/12
#Modified by T.Sekiguchi 2015/08/03

#SET RAMP TIME
tdswrite K1:VIS-PROTO_F0_SERVOF_L_TRAMP 10.0
tdswrite K1:VIS-PROTO_F0_SERVOF_T_TRAMP 10.0
tdswrite K1:VIS-PROTO_F0_SERVOF_Y_TRAMP 10.0
tdswrite K1:VIS-PROTO_IM_SERVOF_L_TRAMP 5.0
tdswrite K1:VIS-PROTO_IM_SERVOF_T_TRAMP 5.0
tdswrite K1:VIS-PROTO_IM_SERVOF_V_TRAMP 5.0
tdswrite K1:VIS-PROTO_IM_SERVOF_R_TRAMP 5.0
tdswrite K1:VIS-PROTO_IM_SERVOF_P_TRAMP 5.0
tdswrite K1:VIS-PROTO_IM_SERVOF_Y_TRAMP 5.0
tdswrite K1:VIS-PROTO_TM_SERVOF_L_TRAMP 5.0
tdswrite K1:VIS-PROTO_TM_SERVOF_P_TRAMP 5.0
tdswrite K1:VIS-PROTO_TM_SERVOF_Y_TRAMP 5.0
tdswrite K1:VIS-PROTO_GAS_COILOUTF_F0_TRAMP 20.0
tdswrite K1:VIS-PROTO_GAS_COILOUTF_F1_TRAMP 20.0
tdswrite K1:VIS-PROTO_GAS_COILOUTF_F2_TRAMP 20.0
tdswrite K1:VIS-PROTO_GAS_SERVOF_F0_TRAMP 10.0
tdswrite K1:VIS-PROTO_GAS_SERVOF_F1_TRAMP 10.0
tdswrite K1:VIS-PROTO_GAS_SERVOF_F2_TRAMP 10.0
tdswrite K1:VIS-PROTO_IM_OPLEVF_P_TRAMP 5.0
tdswrite K1:VIS-PROTO_IM_OPLEVF_Y_TRAMP 5.0


#GAIN OFF
tdswrite K1:VIS-PROTO_F0_SERVOF_L_GAIN 0.0
tdswrite K1:VIS-PROTO_F0_SERVOF_T_GAIN 0.0
tdswrite K1:VIS-PROTO_F0_SERVOF_Y_GAIN 0.0
tdswrite K1:VIS-PROTO_IM_SERVOF_L_GAIN 0.0
tdswrite K1:VIS-PROTO_IM_SERVOF_T_GAIN 0.0
tdswrite K1:VIS-PROTO_IM_SERVOF_V_GAIN 0.0
tdswrite K1:VIS-PROTO_IM_SERVOF_R_GAIN 0.0
tdswrite K1:VIS-PROTO_IM_SERVOF_P_GAIN 0.0
tdswrite K1:VIS-PROTO_IM_SERVOF_Y_GAIN 0.0
tdswrite K1:VIS-PROTO_TM_SERVOF_L_GAIN 0.0
tdswrite K1:VIS-PROTO_TM_SERVOF_P_GAIN 0.0
tdswrite K1:VIS-PROTO_TM_SERVOF_Y_GAIN 0.0
tdswrite K1:VIS-PROTO_GAS_SERVOF_F0_GAIN 0.0
tdswrite K1:VIS-PROTO_GAS_SERVOF_F1_GAIN 0.0
tdswrite K1:VIS-PROTO_GAS_SERVOF_F2_GAIN 0.0
tdswrite K1:VIS-PROTO_IM_OPLEVF_P_GAIN 0.0
tdswrite K1:VIS-PROTO_IM_OPLEVF_Y_GAIN 0.0

#OFFSET
tdswrite -sw K1:VIS-PROTO_GAS_COILOUTF_F2 OFFSET OFF
tdswrite -sw K1:VIS-PROTO_GAS_COILOUTF_F1 OFFSET OFF
tdswrite -sw K1:VIS-PROTO_GAS_COILOUTF_F0 OFFSET OFF

