#!/bin/sh

# by Sekiguchi 2015/08/03

#RAMP
tdswrite K1:VIS-PROTO_IM_SERVOF_P_TRAMP 5.0
tdswrite K1:VIS-PROTO_IM_SERVOF_Y_TRAMP 5.0
tdswrite K1:VIS-PROTO_TM_SERVOF_P_TRAMP 5.0
tdswrite K1:VIS-PROTO_TM_SERVOF_Y_TRAMP 5.0

#OSEM SERVO OFF
tdswrite K1:VIS-PROTO_IM_SERVOF_P_GAIN 0.0
tdswrite K1:VIS-PROTO_IM_SERVOF_Y_GAIN 0.0
tdswrite K1:VIS-PROTO_TM_SERVOF_P_GAIN 0.0
tdswrite K1:VIS-PROTO_TM_SERVOF_Y_GAIN 0.0

#WAIT
sleep 5

#CLEAR
tdswrite K1:VIS-PROTO_IM_OPLEVF_P_RSET 2
tdswrite K1:VIS-PROTO_IM_OPLEVF_Y_RSET 2

#SET RAMP TIME
tdswrite K1:VIS-PROTO_IM_OPLEVF_P_TRAMP 5.0
tdswrite K1:VIS-PROTO_IM_OPLEVF_Y_TRAMP 5.0

#GAIN ON
tdswrite K1:VIS-PROTO_IM_OPLEVF_P_GAIN -1.0
tdswrite K1:VIS-PROTO_IM_OPLEVF_Y_GAIN -1.0




