#!/bin/sh

#Modified by A.Shoda 2015/6/12

#RAMP
tdswrite K1:VIS-PROTO_F0_SERVOF_L_RSET 2
tdswrite K1:VIS-PROTO_F0_SERVOF_T_RSET 2
tdswrite K1:VIS-PROTO_F0_SERVOF_Y_RSET 2


#SET RAMP TIME
tdswrite K1:VIS-PROTO_F0_SERVOF_L_TRAMP 10.0
tdswrite K1:VIS-PROTO_F0_SERVOF_T_TRAMP 10.0
tdswrite K1:VIS-PROTO_F0_SERVOF_Y_TRAMP 10.0

#GAIN ON
tdswrite K1:VIS-PROTO_F0_SERVOF_L_GAIN -1.0
tdswrite K1:VIS-PROTO_F0_SERVOF_T_GAIN -1.0
tdswrite K1:VIS-PROTO_F0_SERVOF_Y_GAIN -1.0


